# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fingerprint_pb2 as fingerprint__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fingerprint_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FingerprintServiceStub(object):
    """Fingerprint service for high-performance audio analysis
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeFingerprint = channel.unary_unary(
                '/fingerprint.FingerprintService/ComputeFingerprint',
                request_serializer=fingerprint__pb2.FingerprintRequest.SerializeToString,
                response_deserializer=fingerprint__pb2.FingerprintResponse.FromString,
                _registered_method=True)


class FingerprintServiceServicer(object):
    """Fingerprint service for high-performance audio analysis
    """

    def ComputeFingerprint(self, request, context):
        """Compute 25D audio fingerprint from raw audio samples
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FingerprintServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeFingerprint': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeFingerprint,
                    request_deserializer=fingerprint__pb2.FingerprintRequest.FromString,
                    response_serializer=fingerprint__pb2.FingerprintResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fingerprint.FingerprintService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fingerprint.FingerprintService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FingerprintService(object):
    """Fingerprint service for high-performance audio analysis
    """

    @staticmethod
    def ComputeFingerprint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fingerprint.FingerprintService/ComputeFingerprint',
            fingerprint__pb2.FingerprintRequest.SerializeToString,
            fingerprint__pb2.FingerprintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
