# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fingerprint.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fingerprint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66ingerprint.proto\x12\x0b\x66ingerprint\"d\n\x12\x46ingerprintRequest\x12\x10\n\x08track_id\x18\x01 \x01(\r\x12\x15\n\raudio_samples\x18\x02 \x03(\x02\x12\x13\n\x0bsample_rate\x18\x03 \x01(\r\x12\x10\n\x08\x63hannels\x18\x04 \x01(\r\"\x8a\x05\n\x13\x46ingerprintResponse\x12\x10\n\x08track_id\x18\x01 \x01(\r\x12\x1a\n\x12processing_time_ms\x18\x02 \x01(\x04\x12\x14\n\x0csub_bass_pct\x18\x03 \x01(\x02\x12\x10\n\x08\x62\x61ss_pct\x18\x04 \x01(\x02\x12\x13\n\x0blow_mid_pct\x18\x05 \x01(\x02\x12\x0f\n\x07mid_pct\x18\x06 \x01(\x02\x12\x15\n\rupper_mid_pct\x18\x07 \x01(\x02\x12\x14\n\x0cpresence_pct\x18\x08 \x01(\x02\x12\x0f\n\x07\x61ir_pct\x18\t \x01(\x02\x12\x0c\n\x04lufs\x18\n \x01(\x02\x12\x10\n\x08\x63rest_db\x18\x0b \x01(\x02\x12\x16\n\x0e\x62\x61ss_mid_ratio\x18\x0c \x01(\x02\x12\x11\n\ttempo_bpm\x18\r \x01(\x02\x12\x18\n\x10rhythm_stability\x18\x0e \x01(\x02\x12\x19\n\x11transient_density\x18\x0f \x01(\x02\x12\x15\n\rsilence_ratio\x18\x10 \x01(\x02\x12\x19\n\x11spectral_centroid\x18\x11 \x01(\x02\x12\x18\n\x10spectral_rolloff\x18\x12 \x01(\x02\x12\x19\n\x11spectral_flatness\x18\x13 \x01(\x02\x12\x16\n\x0eharmonic_ratio\x18\x14 \x01(\x02\x12\x17\n\x0fpitch_stability\x18\x15 \x01(\x02\x12\x15\n\rchroma_energy\x18\x16 \x01(\x02\x12\x1f\n\x17\x64ynamic_range_variation\x18\x17 \x01(\x02\x12\x1e\n\x16loudness_variation_std\x18\x18 \x01(\x02\x12\x18\n\x10peak_consistency\x18\x19 \x01(\x02\x12\x14\n\x0cstereo_width\x18\x1a \x01(\x02\x12\x19\n\x11phase_correlation\x18\x1b \x01(\x02\x32m\n\x12\x46ingerprintService\x12W\n\x12\x43omputeFingerprint\x12\x1f.fingerprint.FingerprintRequest\x1a .fingerprint.FingerprintResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fingerprint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FINGERPRINTREQUEST']._serialized_start=34
  _globals['_FINGERPRINTREQUEST']._serialized_end=134
  _globals['_FINGERPRINTRESPONSE']._serialized_start=137
  _globals['_FINGERPRINTRESPONSE']._serialized_end=787
  _globals['_FINGERPRINTSERVICE']._serialized_start=789
  _globals['_FINGERPRINTSERVICE']._serialized_end=898
# @@protoc_insertion_point(module_scope)
