"""
Harmonic Exciter
~~~~~~~~~~~~~~~~

Generate upper-octave harmonics from midrange content to restore brightness
in bandwidth-limited or dark recordings (lo-fi captures, old broadcasts, low-bitrate
codecs that strip everything above ~8 kHz, etc.).

A shelf EQ can only amplify what already exists. When the source has effectively
no energy above 5 kHz, no amount of high-shelf boost will sound "crispy" — there
is nothing there to lift. This module *synthesizes* new high-frequency content
that correlates musically with the source by saturating its midrange, isolating
the upper harmonics generated by the saturation, and mixing them in parallel.

Signal flow:
    source ──┬─────────────────────────────────────────► dry path ──► +
             │                                                        ▲
             └─► bandpass (donor band) ─► tanh drive ─► HP (keep      │
                                          (asymmetric                  │
                                          if requested)                │
                                          ─► gain (wet level) ────────┘

The asymmetry option biases the saturation curve so it generates both even
and odd harmonics. Even harmonics sound "warm/musical" (tube-like); pure odd
harmonics (symmetric tanh) sound "harsher/edgier" (solid-state). The default
mixes both, biased toward even, so it lifts air without sounding fizzy.

:copyright: (C) 2024 Auralis Team
:license: GPLv3, see LICENSE for more details.
"""

import numpy as np
from scipy.signal import butter, sosfilt


class HarmonicExciter:
    """
    Generate upper-octave harmonics from a donor midrange band.

    The donor band (typically 1–4 kHz) is the source of fundamentals. Saturating
    it with tanh generates harmonics at 2×, 3×, 4×... the donor frequencies, which
    land in presence/brilliance/air. A high-pass on the saturated signal removes
    the regenerated fundamentals so the parallel mix doesn't muddy the midrange.

    All methods are static — no instance state.
    """

    @staticmethod
    def apply(
        audio: np.ndarray,
        sample_rate: int,
        wet_db: float,
        drive_db: float = 12.0,
        donor_low_hz: float = 1000.0,
        donor_high_hz: float = 4000.0,
        hp_cutoff_hz: float = 4500.0,
        asymmetry: float = 0.3,
        order: int = 2,
    ) -> np.ndarray:
        """
        Apply harmonic excitation in parallel with the dry signal.

        Args:
            audio: Input audio, (channels, samples) or (samples,)
            sample_rate: Sample rate in Hz
            wet_db: Level of the generated harmonics relative to dry, in dB
                (e.g. -18 dB ≈ subtle, -12 dB ≈ noticeable, -6 dB ≈ obvious).
                If wet_db <= -60 the input is returned unchanged.
            drive_db: Pre-gain into the saturator. Higher drive = richer / more
                harmonics, but also more intermodulation. Typical range 6–18 dB.
            donor_low_hz: Lower bound of the donor bandpass
            donor_high_hz: Upper bound of the donor bandpass
            hp_cutoff_hz: High-pass cutoff applied AFTER saturation. Should sit
                above donor_high_hz so the parallel mix only adds new harmonics
                (not regenerated copies of the donor band itself).
            asymmetry: 0.0 = pure tanh (odd harmonics only, transistor-like).
                Positive values bias the saturator and add even harmonics
                (tube-like warmth). Range [0.0, 1.0]; 0.2–0.4 is musical.
            order: Filter order (default 2 for gentle slopes that don't ring).

        Returns:
            Audio with the same shape and dtype as input.

        Notes:
            - Pure parallel processing: the dry signal is never altered, only
              augmented. Worst case (heavily clipped wet) only changes upper
              harmonics that the limiter and shelf EQs downstream can still
              shape.
            - Filter order is intentionally low. Steep filters ring on
              transients, which an exciter would then turn into upper-harmonic
              ringing — exactly the artifact we want to avoid.
        """
        if wet_db <= -60.0:
            return audio

        nyquist = sample_rate / 2.0

        # --- 1. Extract donor band (midrange that has actual energy) ---
        low_norm = min(0.99, max(0.01, donor_low_hz / nyquist))
        high_norm = min(0.99, max(0.01, donor_high_hz / nyquist))
        if low_norm >= high_norm:
            # Degenerate band (e.g. very low sample rate) — no exciter possible.
            return audio
        bp_sos = butter(order, [low_norm, high_norm], btype='band', output='sos')

        # --- 2. Saturate to generate harmonics ---
        # Pre-gain controls how hard we drive tanh. tanh is naturally bounded
        # to [-1, 1], so we don't need a post-limiter on the wet path.
        drive_linear = 10.0 ** (drive_db / 20.0)

        # --- 3. High-pass to keep only the *new* harmonics ---
        hp_norm = min(0.99, max(0.01, hp_cutoff_hz / nyquist))
        hp_sos = butter(order, hp_norm, btype='high', output='sos')

        # --- 4. Wet gain (so the parallel mix lands at wet_db below dry) ---
        wet_linear = 10.0 ** (wet_db / 20.0)

        axis = -1 if audio.ndim > 1 else 0

        # sosfilt always returns float64; cast back so we don't promote the
        # mixed signal (same dtype concern as ParallelEQUtilities, issue #2158).
        donor = np.asarray(sosfilt(bp_sos, audio, axis=axis), dtype=audio.dtype)
        driven = donor * np.asarray(drive_linear, dtype=audio.dtype)

        if asymmetry > 0.0:
            # Bias the input by `asymmetry` before tanh, then subtract tanh(bias)
            # so the wet signal stays roughly centered around zero (avoids a DC
            # offset, which downstream filters would have to deal with).
            bias = np.asarray(asymmetry, dtype=audio.dtype)
            saturated = np.tanh(driven + bias) - np.tanh(bias)
        else:
            saturated = np.tanh(driven)

        harmonics = np.asarray(sosfilt(hp_sos, saturated, axis=axis), dtype=audio.dtype)

        return (audio + harmonics * np.asarray(wet_linear, dtype=audio.dtype)).astype(audio.dtype)
